# Generated by Django 5.0.1 on 2024-01-15 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('rate', models.FloatField()),
                ('screen', models.CharField(max_length=5)),
                ('language', models.CharField(max_length=30)),
                ('duration', models.CharField(max_length=4)),
                ('category', models.CharField(max_length=15)),
                ('certification', models.CharField(max_length=5)),
                ('date', models.DateField()),
                ('image', models.ImageField(upload_to='todoimage')),
                ('banner', models.ImageField(upload_to='todoimage')),
                ('description', models.CharField(max_length=200)),
            ],
        ),
    ]
